spring:
  aop:
    proxyTargetClass: true
  application:
    name: zuul
  sleuth:
    sampler:
      percentage: 1.0
  rabbitmq:
    host: rabbitmq.dh.com
    port: 5672
    username: test
    password: test
    virtual-host: test

# Define the port where the API gateway server would be running
server:
  port: 3334
  context-path: /
  session:
      cookie:
        name: zuuloauth

# Define the Eureka server that handles service registration
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.242:8761/eureka/,http://192.168.1.243:8761/eureka/,http://192.168.1.244:8761/eureka/

zuul:
  routes:
    auth-client: /authclient/**
    auth-client2: /authclient2/**
    gumiho_admin_web: /admin/**
    authserver:
      #sensitiveHeaders:
      path: /uaa/**
      stripPrefix: false
  add-proxy-headers: true
  ignored-services: '*'
  force-original-query-string-encoding: false
  add-host-header: true


security:
  oauth2:
    client:
      accessTokenUri: http://oauth2.dh.com:8889/uaa/oauth/token
      userAuthorizationUri: http://oauth2.dh.com:8889/uaa/oauth/authorize
      clientId: zuul
      clientSecret: zuul
      scope: all
      id: zull
      registered-redirect-uri:
    resource:
      id: zuul
      token-info-uri: http://oauth2.dh.com:8889/uaa/oauth/check_token
      user-info-uri: http://oauth2.dh.com:8889/uaa/oauth/user
    sso:
      login-path: /login
  basic:
    enabled: true
  user:
    password: ly
    name: ly


logging:
  config: classpath:log4j2.yml

management:
  security:
    enabled: true






