
server:
  port: 5001
  servlet:
    context-path: /




spring:
  application:
    name: server-consume
  rabbitmq:
    host: rabbitmq.dh.com
    port: 5672
    username: test
    password: test
    virtual-host: test
#  zipkin:
#    base-url: http://zipkinserver/

eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.242:8761/eureka/
    register-with-eureka: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      base-path: /application

endpoints:
  default:
    enabled: true
    web:
      enabled: true
  mappings:
    enabled: true

logging:
  level:
    root: debug