
server:
  port: 5001
  context-path: /




spring:
  application:
    name: server-consume
  rabbitmq:
    host: rabbitmq.dh.com
    port: 5672
    username: hystrix
    password: hystrix
    virtual-host: hystrix
#  zipkin:
#    base-url: http://zipkinserver/

eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.242:8761/eureka/
    register-with-eureka: true
  instance:
    prefer-ip-address: true


logging:
  level:
    root: INFO

