spring:
  application:
    name: authserver
  datasource:
    name: oauth
    url: jdbc:mysql://192.168.1.204:3306/cloud_auth
    username: cloud
    password: cloud
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 14
    host: 192.168.1.203
    prot: 6379
    password:

# Define the port where the UAA server would be running
server:
  port: 8889
  # Use different context-path to avoid session cookie overlapping
  context-path: /uaa
#  use-forward-headers: true

# Define the Eureka server that handles service registration
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.242:8761/eureka/,http://192.168.1.243:8761/eureka/,http://192.168.1.244:8761/eureka/
  instance:
    prefer-ip-address: true
# Define security
security:
  basic:
    enabled: false
  user:
    password: password

logging:
  level.root: DEBUG
  file: ./logs/log.log
  level.org.apache.http: INFO
  level.com.netflix.discovery: INFO




