spring:
  profiles:
    include: myproject
  application:
      name: zipkinserver1
  rabbitmq:
    host: rabbitmq.dh.com
    port: 5672
    username: hystrix
    password: hystrix
    virtual-host: hystrix

eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.242:8761/eureka



