debug: true
server:
  port: 9999
  #contextPath: /sso

security:
  ignored: /,/favicon.ico,/index.html,/home.html,/dashboard.html,/js/**,/css/**,/webjars/**
  sessions: ALWAYS
  oauth2:
    sso:
      loginPath: /dashboard/login

logging:
  level:
    org.springframework.security: DEBUG
spring:
  application:
    name: sso

#
#zuul:
#  routes:
#    a1:
#      path: /dashboard/a1/**
#      url: http://192.168.2.230:2222/


---
spring:
  profiles: default
security:
  oauth2:
    client:
      accessTokenUri: http://127.0.0.1:8888/uaa/oauth/token
      userAuthorizationUri: http://127.0.0.1:8888/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
      scope: write
    resource:
      userInfoUri: http://127.0.0.1:8888/uaa/user/
      preferTokenInfo: false
#      jwt:
#        keyValue: |
#          -----BEGIN PUBLIC KEY-----
#          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6uR3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5XaA0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqynT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQyzKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sfZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscuWG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22CIMuIeRLVcAmEWEWH5EEforTg+QIDAQAB
#          -----END PUBLIC KEY-----
#      id: openid
#      serviceId: ${PREFIX:}resource


    