# Define the port where the UAA server would be running
server:
  port: 3333
  # Use different context-path to avoid session cookie overlapping
  context-path: /
#  use-forward-headers: true

mybatis:
  #mapper-locations: classpath:cn.waicaibao.user.mapper/*.xml
  #type-aliases-package: classpath:cn.waicaibao.user.entity
  config-location: classpath:mybatis-config.xml

logging:
  level.root: DEBUG
  file: ./logs/log.log
  level.org.apache.http: INFO
  level.com.netflix.discovery: INFO

pagehelper:
  params: pageNum=pageNumKey;pageSize=pageSizeKey;

aliyun:
  oss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-secret: mAYn0GtMRUWPJX4NFRTie2IztgrC8r
    access-key-id: LTAIoNYCQixwQrRo
    bucket-name: dh-demo
  push:
    app-key: 24557719
    app-secret: q7YAaHByaaDwqFTEYi6mvi0z5NPrVo
    app-key-id: LTAIoA2cncXLDeej
sms:
  zhutong:
    url: http://www.ztsms.cn/sendNSms.do
    username: dongheng
    password: pkDuLx8f
    productid: 676767
    signature: 【myproject】
    productid2: 887362
    productid3: 435227
    batchurl: http://www.ztsms.cn/sendManyNSms.do
    gurl: http://www.ztsms.cn/sendGSms.do


spring:
  application:
    name: admin-api-provide
  datasource:
    name: admin
    url: jdbc:mysql://192.168.1.100:3306/admin
    username: b2b2c
    password: B2b2c1234
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
    database: 9
    host: 127.0.0.1
    prot: 6379
    password:


eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.100:1111/eureka/
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}





