server:
  port: 5555

spring:
  application:
    name: ui
  sleuth:
    sampler:
      percentage: 1.0
  datasource:
    name: oauth
    url: jdbc:mysql://192.168.2.172:3306/waikuai
    username: waikuai
    password: waikuai
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
    database: 9
    host: 192.168.2.204
    prot: 6379
    password: foobared
  rabbitmq:
    host: 192.168.2.231
    port: 5672
    username: wcbtest
    password: wcbtest
    virtual-host: wcbtest
security:
  #sessions: ALWAYS
  oauth2:
    sso:
      loginPath: /login
    client:
      accessTokenUri: http://192.168.2.230:3333/uaa/oauth/token
      userAuthorizationUri: http://192.168.2.230:3333/uaa/oauth/authorize
      clientId: ui
      clientSecret: uisecret
      scope: write
    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6uR3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5XaA0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqynT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQyzKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sfZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscuWG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22CIMuIeRLVcAmEWEWH5EEforTg+QIDAQAB
          -----END PUBLIC KEY-----
#      id: uiid
#      serviceId: ${PREFIX:}uiresource

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.2.227:1111/eureka/,http://192.168.2.228:1111/eureka/,http://192.168.2.229:1111/eureka/
  instance:
    prefer-ip-address: true

logging:
  config: classpath:log4j2.yml