server:
  port: 5555
  context-path: /ui


spring:
  application:
    name: ui
  redis:
    database: 8
    host: 192.168.2.204
    prot: 6379
    password: foobared

security:
  ignored: /,/favicon.ico,/index.html,/home.html,/dashboard.html,/js/**,/css/**,/webjars/**
  # Disable Spring Boot basic authentication
  basic:
    enabled: false
  sessions: ALWAYS
  oauth2:
    sso:
      loginPath: /login
    client:
      accessTokenUri: http://127.0.0.1:8888/uaa/oauth/token
      userAuthorizationUri: http://127.0.0.1:8888/uaa/oauth/authorize
      clientId: ui
      clientSecret: uisecret
      scope: write
    resource:
      user-info-uri: http://127.0.0.1:8888/uaa/user
      prefer-token-info: false

#      jwt:
#        keyValue: |
#          -----BEGIN PUBLIC KEY-----
#          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6uR3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5XaA0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqynT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQyzKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sfZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscuWG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22CIMuIeRLVcAmEWEWH5EEforTg+QIDAQAB
#          -----END PUBLIC KEY-----
#      id: openid
#      serviceId: ${PREFIX:}resource

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.2.227:1111/eureka/,http://192.168.2.228:1111/eureka/,http://192.168.2.229:1111/eureka/
  instance:
    prefer-ip-address: true
logging:
  config: classpath:log4j2.yml