
server:
  port: 3334
  context-path: /


mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  #type-aliases-package: classpath:cn.com.myproject.user.entity
  config-location: classpath:mybatis-config.xml

logging:
  config: classpath:log4j2.yml


pagehelper:
  params: pageNum=pageNumKey;pageSize=pageSizeKey;

aliyun:
  oss:
    endpoint: oss-cn-hongkong.aliyuncs.com
    access-key-secret: XWwSMQFfcFEisPBJXoYOoGuDHwL66N
    access-key-id: LTAIPOcxLTWiB6yH
    bucket-name: sjjimg
    return-url-prefix: http://a.myproject.com.cn/
  push:
    app-key: 24613456
    app-secret: uAyhEQoaypoEPy9zFU4fAY7aj9TmrH
    app-key-id: LTAIWPmZiJa5FSdO
    region-id: cn-hangzhou
    i-o-s-apns-env: PRODUCT

spring:
  application:
    name: gumiho-admin-user
  datasource:
    name: admin
    url: jdbc:mysql://mysql01.dh.com:3306/cloud_auth?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true&useSSL=true&allowMultiQueries=true
    username: cloud
    password: cloud
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
    database: 11
    host: redis01.dh.com
    prot: 6379
    password:
  servlet:
    multipart:
      max-file-size: 2048mb
      max-request-size: 2048mb
  rabbitmq:
    host: rabbitmq.dh.com
    port: 5672
    username: test
    password: test
    virtual-host: test
  zipkin:
    base-url: http://zipkinserver/

eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.242:8761/eureka/,http://192.168.1.243:8761/eureka/,http://192.168.1.244:8761/eureka/
    register-with-eureka: true
  instance:
    prefer-ip-address: true

    #instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}


