spring:
  application:
    name: elasticsearch
  data:
    elasticsearch:
      cluster-name: es
      cluster-nodes: es.dh.com:9300
  datasource:
    name: oauth
    url: jdbc:mysql://192.168.1.204:3306/cloud_auth
    username: cloud
    password: cloud
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
# Define the port where the UAA server would be running
server:
  port: 7777
  servlet:
    context-path: /
  # Use different context-path to avoid session cookie overlapping
#  use-forward-headers: true




logging:
  level.root: DEBUG
  file: ./logs/log.log
  level.org.apache.http: INFO
  level.com.netflix.discovery: INFO

eureka:
  client:
    service-url:
      defaultZone: http://eureka242.dh.com:1111/eureka/

management:
  security:
    enabled: false #测试用，线上必须为true



